name = "chromatic"
version = "1.0.0"

description = "Beautiful, expressive and composable color and text formatting for CLI in Gleam."
licences = ["MIT"]
repository = { type = "github", user = "joshocalico", repo = "chromatic" }
links = [{ title = "Website", href = "https://github.com/joshocalico/chromatic" }]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
